Vagrant.configure("2") do |config|

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "generic/ubuntu2204"
	ansible.vm.network "private_network", ip: "10.10.1.50"
	ansible.vm.provider "vmware_workstation" do |vb|
          vb.memory = "1024"
        end
    end
  end
